### ISSUE TITLE
idea, use lightweight http server

### ISSUE THREAD

**Issue by debris** [ethcore/jsonrpc#11]
Currently `jsonrpc-http-server` uses `hyper`. And since I remember there were some issues with it (that's why we have forked it). What do you think about replacing hyper with some other / smaller library? eg. [tiny-http](https://github.com/frewsxcv/tiny-http)

**Comment by tomusdrw** [comment]
`tiny-http` is using thread pool, would be best to have something based on event loop instead

**Comment by tomusdrw** [comment]
Might want to check out https://github.com/tokio-rs/tokio-minihttp
