### ISSUE TITLE
migrate to serde 0.9

### ISSUE THREAD

**Issue by vitiral** [ethcore/jsonrpc#39]
rust 0.15 was just released and with it custom `derive`!

Serde released version 0.9, which is now incompatible with this library:

```
error[E0308]: mismatched types
  --> src/api/handler.rs:40:12
   |
40 |         Ok(value)
   |            ^^^^^ expected enum `jsonrpc_core::Value`, found enum `serde_json::Value`
   |
   = note: expected type `jsonrpc_core::Value`
   = note:    found type `serde_json::Value`
```

migrating shouldn't be difficult. If you would like, I can open a pull request.

**Comment by tomusdrw** [comment]
It's already fixed in #38, we're just awaiting to release a new version which should happen soon.

**Comment by tomusdrw** [comment]
`jsonrpc-core = 6.0` with serde-0.9 was just recently released, make sure to try it out :)

**Comment by vitiral** [comment]
awesome thanks! Great library btw -- I use it with nickel (currently) and it integrates seamlessly.
