### ISSUE TITLE
Request handler returns jsonrpc field as `null`

### ISSUE THREAD

**Issue by NikVolf** [ethcore/jsonrpc#42]
```
2017-02-13 17:24:39   TRACE tcp  Sent response: {"jsonrpc":null,"result":true,"id":1}
```

That field supposed to be `2.0` for json-rpc 2.0 and ommited for json-rpc 1.0 (or at least be `1.0`)

**Comment by tomusdrw** [comment]
https://github.com/serde-rs/serde-rs.github.io/blob/master/src/attr-skip-serializing.md

**Comment by NikVolf** [comment]
yeah sure i will make a pr shortly, currently reproducing with a test
