### ISSUE TITLE
Maintain 'stable' branch

### ISSUE THREAD

**Issue by NikVolf** [ethcore/jsonrpc#68]
As it is now, if some urgent fix is required by `parity`, we will have to create separate branch for it and update parity `Cargo.toml` to use this new branch. This is because `jsonrpc/master` usually contains breaking changes and `parity` cannot be just updated to this latest master.

**Comment by NikVolf** [comment]
@tomusdrw if you agree there is a `stable` branch now, it is made from the latest commit that parity currently uses.

**Comment by tomusdrw** [comment]
Sure, make sesne. I would rather propose to call branches with Parity version in them, like `parity-1.5`, calling them `stable` or `beta` is a bit confusing especially when some version is moved from `beta` to `stable` later.
